#!/bin/bash
# runMafJoin [options] guideGenome inMaf1 inMaf2 outMaf
#  
# script to run mafJoin for evolver testing, simplifying calling by generating the names of
# derived files

set -beEu -o pipefail

cmd="../../../../bin/mafJoin"

haveTreelessRoot1=no
haveTreelessRoot2=no
while [[ $1 == -* ]] ; do
    cmd="$cmd $1"
    case $1 in
        -treelessRoot1=*) haveTreelessRoot1=yes;;
        -treelessRoot2=*) haveTreelessRoot2=yes;;
    esac
    shift
done

if [ $# != 4 ] ; then
    echo "Error: wrong # args" >&2
    exit 1
fi
guideGenome="$1"
inMaf1="$2"
inMaf2="$3"
outMaf="$4"
outMafTmp=$outMaf.$$.tmp
outPrefix=$(echo $outMaf | sed 's/[.][^/]*$//')
err=$outPrefix.err

if true ; then
    # add dump options
    cmd="$cmd -inMaf1Dump=${outPrefix}.in1.dmp -inMaf2Dump=${outPrefix}.in2.dmp -outMafDump=${outPrefix}.out.dmp"
fi
cmd="$cmd $guideGenome $inMaf1 $inMaf2 $outMafTmp"

mkdir -p $(dirname $outMaf)
set -x
$cmd >&$err
mv -f $outMafTmp $outMaf

if true ; then
    cmpXmlOut=$outPrefix.stepcmp.xml
    cmpDetailOut=$outPrefix.stepcmp.details
    if [ ${haveTreelessRoot1} = "yes" -a  ${haveTreelessRoot2} = "no" ] ; then
        eval_MAFComparator --mAFFile1 $inMaf1  --mAFFile2 $outMaf --outputFile $cmpXmlOut --ultraVerbose >& $cmpDetailOut
    fi
    if [ ${haveTreelessRoot1} = "no" -a  ${haveTreelessRoot2} = "yes" ] ; then
        eval_MAFComparator --mAFFile1 $inMaf2  --mAFFile2 $outMaf --outputFile $cmpXmlOut --ultraVerbose >& $cmpDetailOut
    fi
fi
